globalThis.process ??= {}; globalThis.process.env ??= {};
import { c as createAstro, a as createComponent, r as renderTemplate, m as maybeRenderHead, b as addAttribute, d as renderHead, e as renderSlot, f as renderComponent, $ as $$Image } from '../renderers.mjs';
import './kleur_BcFxsYqz.mjs';
/* empty css                          */
/* empty css                           */
import { c as create_ssr_component, o as onMount } from './svelte_BCRmTjIV.mjs';
/* empty css                         */

const $$Astro$f = createAstro();
const $$Contact$1 = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$f, $$props, $$slots);
  Astro2.self = $$Contact$1;
  return renderTemplate`${maybeRenderHead()}<section class="bg-white dark:bg-gray-900"> <div class="py-8 lg:py-16 px-4 mx-auto max-w-screen-md"> <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white">
Contact Us
</h2> <p class="mb-8 lg:mb-16 font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl">
Got a technical issue? Want to send feedback about a beta feature?
            Need details about our Business plan? Let us know.
</p> <form action="#" class="space-y-8"> <div> <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Your email</label> <input type="email" id="email" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" placeholder="name@flowbite.com" required> </div> <div> <label for="subject" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Subject</label> <input type="text" id="subject" class="block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" placeholder="Let us know how we can help you" required> </div> <div class="sm:col-span-2"> <label for="message" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400">Your message</label> <textarea id="message" rows="6" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Leave a comment..."></textarea> </div> <button type="submit" class="py-3 px-5 text-sm font-medium text-center text-white rounded-lg bg-primary-700 sm:w-fit hover:bg-primary-800 bg-primary focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Send message</button> </form> </div> </section>`;
}, "C:/Users/aradh/git/MMM/src/components/Contact.astro", void 0);

const $$Astro$e = createAstro();
const $$Layout = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$e, $$props, $$slots);
  Astro2.self = $$Layout;
  const { title } = Astro2.props;
  return renderTemplate`<html lang="en" data-astro-cid-sckkx6r4> <head><meta charset="UTF-8"><meta name="description" content="Astro description"><meta name="viewport" content="width=device-width"><link rel="icon" type="image/svg+xml" href="/favicon.png"><meta name="generator"${addAttribute(Astro2.generator, "content")}><title>${title}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">${renderHead()}</head> <body class="bg-bg" data-astro-cid-sckkx6r4> ${renderSlot($$result, $$slots["default"])}  </body></html>`;
}, "C:/Users/aradh/git/MMM/src/layouts/Layout.astro", void 0);

/* C:/Users/aradh/git/MMM/src/components/Header.svelte generated by Svelte v4.2.12 */

const css = {
	code: "li.svelte-n9y89b{font-family:\"Syne\", sans-serif}.fixIt.svelte-n9y89b{background:rgba(0, 0, 0, 0.9);position:fixed}",
	map: null
};

const Header = create_ssr_component(($$result, $$props, $$bindings, slots) => {

	// let kk = $state(0);
	let sticky = false;

	onMount(function () {
		function ak() {
			if (window.scrollY > document.querySelector("#header").offsetTop) {
				sticky = true;
			} else sticky = false;
		}

		window.onscroll = function () {
			ak();
		};
	});

	$$result.css.add(css);

	return `<header id="header" class="${[
		"w-full h-[8vh] p-1 py-2 shadow-sm absolute shadow-secondary text-white bg-bg/10 z-40 items-center justify-between md:px-5 bg-red flex svelte-n9y89b",
		sticky ? "fixIt" : ""
	].join(' ').trim()}"><p class="logo w-auto mx-5 h-full" data-svelte-h="svelte-10gbewt"><img src="/logo_white.svg" alt="" srcset="" class="h-full"></p> <ul class="${[
		"md:w-[60%] h-screen md:h-full w-0 absolute justify-center md:static left-0 mt-[80vh] md:mt-0 text-center items-center bg-bg/90 backdrop:blur-lg md:bg-bg/10 overflow-hidden flex flex-col md:flex-row z-10 text-xl transition-all",
		""
	].join(' ').trim()}" data-svelte-h="svelte-1vqobs4"><li class="m-10 svelte-n9y89b"><a href="/">Home</a></li> <hr class="md:hidden bg-slate-800 w-3/4 text-center opacity-30"> <li class="m-10 svelte-n9y89b"><a href="/#about">About</a></li> <hr class="bg-slate-800 md:hidden w-3/4 text-center opacity-30"> <li class="m-10 svelte-n9y89b"><a href="/services">Service</a></li> <hr class="bg-slate-800 md:hidden w-3/4 text-center opacity-30"> <li class="m-10 svelte-n9y89b"><a href="/contact">Contact Us</a></li> <hr class="bg-slate-800 md:hidden w-3/4 text-center opacity-30"> <div class="mt-10 max-w-60 md:hidden text-xl text-black bg-primary px-10 py-5 rounded-full font-semibold">Reach Out to Us</div></ul> <div class="md:text-xl md:block hidden text-lg text-black bg-primary px-4 py-2 rounded-full font-semibold" data-svelte-h="svelte-1xz87v1">Reach Out to Us</div> <i class="${[
		"md:hidden mx-10 z-20 text-primary scale-150 cursor-pointer hover:scale-125",
		""
	].join(' ').trim()}" data-svelte-h="svelte-1i7gvk1"><img src="/Hamburger.svg" alt="" srcset=""></i> </header>`;
});

const $$Astro$d = createAstro();
const $$Contact = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$d, $$props, $$slots);
  Astro2.self = $$Contact;
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "title": "Contact Us" }, { "default": ($$result2) => renderTemplate` ${renderComponent($$result2, "Header", Header, {})} ${renderComponent($$result2, "ContactUs", $$Contact$1, {})} ` })}`;
}, "C:/Users/aradh/git/MMM/src/pages/contact.astro", void 0);

const $$file$4 = "C:/Users/aradh/git/MMM/src/pages/contact.astro";
const $$url$4 = "/contact";

const contact = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
    __proto__: null,
    default: $$Contact,
    file: $$file$4,
    url: $$url$4
}, Symbol.toStringTag, { value: 'Module' }));

const $$Astro$c = createAstro();
const $$Card = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$c, $$props, $$slots);
  Astro2.self = $$Card;
  const {
    title = "[ Title ]",
    explanation = " [Explanation] ",
    link = "#",
    img = "/imagePlaceholder.svg"
  } = Astro2.props;
  return renderTemplate`${maybeRenderHead()}<div class="max-w-sm w-64 h-auto md:p-6 p-2 md:mx-5 mx-2 bg-white border border-gray-200 rounded-lg shadow dark:bg-secondary dark:border-gray-700"> <img${addAttribute(img, "src")} alt="" width="100" class="m-auto"> <a href="#"> <div class="w-80"></div> <h5 class="mb-2 px-2 text-center md:text-2xl text-xl font-bold tracking-tight text-gray-900 dark:text-white"> ${title} </h5> </a> <!-- <p
		class="mb-3 text-sm px-2 text-justify font-normal h-auto w-[80%] text-gray-700 dark:text-gray-400"
	>
		{explanation}
	</p> --> <a${addAttribute(link, "href")} class="flex m-auto mt-10 justify-center w-[80%] items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
Consult Us
<svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10"> <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"></path> </svg> </a> </div>`;
}, "C:/Users/aradh/git/MMM/src/components/Card.astro", void 0);

const $$Astro$b = createAstro();
const $$Gallery = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$b, $$props, $$slots);
  Astro2.self = $$Gallery;
  const { first, second, third, fourth } = Astro2.props;
  return renderTemplate`${maybeRenderHead()}<h1 class="text-xl mt-20 p-10 underline md:text-4xl">Gallery</h1> <div class="grid grid-cols-2 md:grid-cols-4 p-5 border gap-4"> <div class="grid gap-4"> ${first.map((e) => renderTemplate`<div> <img class=" h-auto max-w-full rounded-lg"${addAttribute(e.default.src, "src")} alt=""> </div>`)} <!-- <div>
            <img
                class="h-auto max-w-full rounded-lg"
                src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-1.jpg"
                alt=""
            />
        </div>
        <div>
            <img
                class="h-auto max-w-full rounded-lg"
                src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-2.jpg"
                alt=""
            />
        </div> --> </div> <div class="grid gap-4"> <!-- <div>
            <img
                class="h-auto max-w-full rounded-lg"
                src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-3.jpg"
                alt=""
            />
        </div>
        <div>
            <img
                class="h-auto max-w-full rounded-lg"
                src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-4.jpg"
                alt=""
            />
        </div>
        <div>
            <img
                class="h-auto max-w-full rounded-lg"
                src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-5.jpg"
                alt=""
            />
        </div> --> ${second.map((e) => renderTemplate`<div> <img class=" h-auto max-w-full rounded-lg"${addAttribute(e.default.src, "src")} alt=""> </div>`)} </div> <div class="grid gap-4"> <!-- <div>
            <img
                class="h-auto max-w-full rounded-lg"
                src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-6.jpg"
                alt=""
            />
        </div>
        <div>
            <img
                class="h-auto max-w-full rounded-lg"
                src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-7.jpg"
                alt=""
            />
        </div>
        <div>
            <img
                class="h-auto max-w-full rounded-lg"
                src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-8.jpg"
                alt=""
            />
        </div> --> ${third.map((e) => renderTemplate`<div> <img class="h-auto max-w-full rounded-lg"${addAttribute(e.default.src, "src")} alt=""> </div>`)} </div> <div class="grid gap-4"> <!-- <div>
            <img
                class="h-auto max-w-full rounded-lg"
                src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-9.jpg"
                alt=""
            />
        </div>
        <div>
            <img
                class="h-auto max-w-full rounded-lg"
                src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-10.jpg"
                alt=""
            />
        </div>
        <div>
            <img
                class="h-auto max-w-full rounded-lg"
                src="https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-11.jpg"
                alt=""
            />
        </div> --> ${fourth.map((e) => renderTemplate`<div> <img class="h-auto max-w-full rounded-lg"${addAttribute(e.default.src, "src")} alt=""> </div>`)} </div> </div>`;
}, "C:/Users/aradh/git/MMM/src/components/Gallery.astro", void 0);

const $$Astro$a = createAstro();
const Astro = $$Astro$a;
async function getStaticPaths() {
  const pages = await Astro.glob(/* #__PURE__ */ Object.assign({"../../data/service/digi-marketing.json": () => import('./digi-marketing_Biv83qku.mjs'),"../../data/service/foodphotography.json": () => import('./foodphotography_CXJFSJfD.mjs'),"../../data/service/photography.json": () => import('./photography_BlBmn8pR.mjs'),"../../data/service/portfolioshoot-.json": () => import('./portfolioshoot-_uajYLE7s.mjs'),"../../data/service/wedding-shoot.json": () => import('./wedding-shoot_CWOkXirB.mjs')}), () => "../../data/service/*.json");
  return pages.map((e) => ({
    params: {
      slag: e.slag
    },
    props: { e }
  }));
}
const $$slag = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$a, $$props, $$slots);
  Astro2.self = $$slag;
  Astro2.params;
  const GImages = await Astro2.glob(/* #__PURE__ */ Object.assign({"../../assets/ambiance/Copy of Copy of DJI_0559-min.JPG": () => import('./Copy of Copy of DJI_0559-min_Cwx5XhHq.mjs'),"../../assets/ambiance/Copy of Copy of DJI_0563-min.JPG": () => import('./Copy of Copy of DJI_0563-min_CSVUsqX8.mjs'),"../../assets/ambiance/Copy of Copy of DJI_0567-min.JPG": () => import('./Copy of Copy of DJI_0567-min_IKLPP9JE.mjs'),"../../assets/ambiance/Copy of Copy of DJI_0579-min.JPG": () => import('./Copy of Copy of DJI_0579-min_DdCADaNf.mjs'),"../../assets/ambiance/Copy of Copy of DJI_0599-min.JPG": () => import('./Copy of Copy of DJI_0599-min_0VFiFhfL.mjs'),"../../assets/ambiance/Copy of Copy of DJI_0611-min.JPG": () => import('./Copy of Copy of DJI_0611-min_DG_Q-_C9.mjs'),"../../assets/ambiance/Copy of Copy of MKP03182-min.jpg": () => import('./Copy of Copy of MKP03182-min_CN1Cn1uU.mjs'),"../../assets/ambiance/Copy of Copy of MKP03186-min.jpg": () => import('./Copy of Copy of MKP03186-min_DUS5QrNZ.mjs'),"../../assets/ambiance/Copy of Copy of MKP03187-min.jpg": () => import('./Copy of Copy of MKP03187-min_CGLSyu3X.mjs'),"../../assets/ambiance/Copy of Copy of MKP03188-min.jpg": () => import('./Copy of Copy of MKP03188-min_CYXjo5Zr.mjs'),"../../assets/ambiance/Copy of Copy of MKP03190-min.jpg": () => import('./Copy of Copy of MKP03190-min_nyvFP0ij.mjs'),"../../assets/ambiance/Copy of Copy of MKP03194-min.jpg": () => import('./Copy of Copy of MKP03194-min_D5ZYgpBX.mjs'),"../../assets/ambiance/Copy of Copy of MKP03229-min.jpg": () => import('./Copy of Copy of MKP03229-min_BpxNzf7K.mjs'),"../../assets/ambiance/Copy of Copy of MKP03231-min.jpg": () => import('./Copy of Copy of MKP03231-min_oYpTfcUw.mjs'),"../../assets/ambiance/Copy of Copy of MKP03303-min.jpg": () => import('./Copy of Copy of MKP03303-min_BInCkn3-.mjs'),"../../assets/ambiance/Copy of Copy of MKP03320-min.jpg": () => import('./Copy of Copy of MKP03320-min_BGqNEtkd.mjs'),"../../assets/ambiance/Copy of Copy of MKP03321-min.jpg": () => import('./Copy of Copy of MKP03321-min_Dajew-lq.mjs'),"../../assets/ambiance/Copy of Copy of MKP03327-min.jpg": () => import('./Copy of Copy of MKP03327-min_Bt8rpgL6.mjs'),"../../assets/ambiance/Copy of Copy of MKP03330-min.jpg": () => import('./Copy of Copy of MKP03330-min_DttMqRPx.mjs'),"../../assets/ambiance/Copy of MKP03682-min.jpg": () => import('./Copy of MKP03682-min_CkqMFzpJ.mjs'),"../../assets/ambiance/Copy of MKP03684-min.jpg": () => import('./Copy of MKP03684-min_bx0CkgO6.mjs')}), () => "../../assets/ambiance/*");
  let img1 = [], img2 = [], img3 = [], img4 = [];
  for (let i = 0; i < GImages.length; i++) {
    if (i <= 4)
      img1.push(GImages[i]);
    else if (i >= 4 && i < 8)
      img2.push(GImages[i]);
    else if (i >= 8 && i < 12)
      img3.push(GImages[i]);
    else if (i >= 12 && i < 16)
      img4.push(GImages[i]);
  }
  console.log(GImages[0]);
  const { e } = Astro2.props;
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "title": e.title + "Service", "data-astro-cid-eja6pend": true }, { "default": ($$result2) => renderTemplate`${renderComponent($$result2, "Header", Header, { "client:load": true, "client:component-hydration": "load", "client:component-path": "C:/Users/aradh/git/MMM/src/components/Header.svelte", "client:component-export": "default", "data-astro-cid-eja6pend": true })}${maybeRenderHead()}<div class="text-white" data-astro-cid-eja6pend><div class="md:pt-20 h-screen relative text-white p-2 bg-bg" data-astro-cid-eja6pend>${renderComponent($$result2, "Image", $$Image, { "src": e.image || "/imagePlaceholder.svg", "alt": "", "width": "100", "height": 1, "class": "h-[80vh] w-[80vw] m-auto", "data-astro-cid-eja6pend": true })}<div class="w-full h-full bg-black/20 top-0 absolute" data-astro-cid-eja6pend><h1 class="text-center m-auto text-6xl -translate-x-1/2 -translate-y-1/2 top-[50%] absolute left-[50%]" data-astro-cid-eja6pend>
Hello world
</h1></div></div><h1 class="md:text-3xl text-2xl md:pl-20 p-10 mb-10" data-astro-cid-eja6pend>${e.title} Service
</h1><div class="bg-secondary py-20 md:flex justify-around md:px-10 rounded-3xl md:w-[80%] w-[98%] m-auto" data-astro-cid-eja6pend><img${addAttribute(e.images[0], "src")} alt="" class="h-full w-full m-auto md:m-0 max-w-48 bg-cover" data-astro-cid-eja6pend><p class="md:text-xl text-sm m-5 md:pr-10 bg-secondary tracking-wider" data-astro-cid-eja6pend>${e.desc}</p></div>${renderComponent($$result2, "Gallery", $$Gallery, { "first": img1, "second": img2, "third": img3, "fourth": img4, "data-astro-cid-eja6pend": true })}<!-- Section --><div class="relative" data-astro-cid-eja6pend><div class="w-full mt-10 relative overflow-auto h-auto md:my-10 py-1 md:px-10 p-1 bg-secondary no-scrollbar border border-[#525350]" data-astro-cid-eja6pend><div class="bg-bg rounded-lg relative p-2 md:p-5 m-auto w-full overflow-hidden no-scrollbar" data-astro-cid-eja6pend><div class="flex overflow-auto" id="slideIt" data-astro-cid-eja6pend>${e.sub_services.map((el) => renderTemplate`${renderComponent($$result2, "Card", $$Card, { "title": el.title, "explanation": el.desc, "data-astro-cid-eja6pend": true })}`)}</div></div></div><button id="scroll-left" class="md:block hidden btn-scroll left-0" data-astro-cid-eja6pend><img src="/arrow.svg" alt="" srcset="" class="w-full h-full" data-astro-cid-eja6pend></button><button id="scroll-right" class="hidden md:block btn-scroll rotate-180 right-0" data-astro-cid-eja6pend><img src="/arrow.svg" alt="" srcset="" class="w-full h-full" data-astro-cid-eja6pend></button></div></div>` })}`;
}, "C:/Users/aradh/git/MMM/src/pages/services/[slag].astro", void 0);

const $$file$3 = "C:/Users/aradh/git/MMM/src/pages/services/[slag].astro";
const $$url$3 = "/services/[slag]";

const _slag_ = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
    __proto__: null,
    default: $$slag,
    file: $$file$3,
    getStaticPaths,
    url: $$url$3
}, Symbol.toStringTag, { value: 'Module' }));

const imgPlaceholder = new Proxy({"src":"/_astro/imagePlaceholder.DquXY3qs.svg","width":16,"height":16,"format":"svg"}, {
						get(target, name, receiver) {
							if (name === 'clone') {
								return structuredClone(target);
							}
							if (name === 'fsPath') {
								return "C:/Users/aradh/git/MMM/public/imagePlaceholder.svg";
							}
							
							return target[name];
						}
					});

const $$Astro$9 = createAstro();
const $$ServiceCardLong = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$9, $$props, $$slots);
  Astro2.self = $$ServiceCardLong;
  const { data } = Astro2.props;
  return renderTemplate`${maybeRenderHead()}<a${addAttribute(data.slug, "href")} class="flex md:m-10 m-2 md:p-5 p-2 w-full flex-col items-center bg-primary border border-gray-200 rounded-lg shadow md:flex-row md:max-w-6xl hover:bg-primary/40 dark:border-gray-700 dark:bg-primary/70 dark:hover:bg-primary/90"> ${renderComponent($$result, "Image", $$Image, { "class": "object-cover rounded-t-lg w-[60%] md:w-full md:max-w-40 min-w-20 md:h-auto md:rounded-none md:rounded-s-lg", "src": imgPlaceholder, "alt": "" })} <div class="flex w-full flex-col justify-between p-4 leading-normal"> <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900"> ${data.title} </h5> <p class="mb-3 font-normal text-gray-700 dark:text-gray-900"> ${data.desc.slice(20)}...
</p> <button class="bg-bg w-fit m-auto px-[20%] text-white p-2 rounded-lg">
Explore More</button> </div> </a>`;
}, "C:/Users/aradh/git/MMM/src/components/util/ServiceCardLong.astro", void 0);

const $$Astro$8 = createAstro();
const $$Index$1 = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$8, $$props, $$slots);
  Astro2.self = $$Index$1;
  const services = await Astro2.glob(/* #__PURE__ */ Object.assign({"../../data/service/digi-marketing.json": () => import('./digi-marketing_Biv83qku.mjs'),"../../data/service/foodphotography.json": () => import('./foodphotography_CXJFSJfD.mjs'),"../../data/service/photography.json": () => import('./photography_BlBmn8pR.mjs'),"../../data/service/portfolioshoot-.json": () => import('./portfolioshoot-_uajYLE7s.mjs'),"../../data/service/wedding-shoot.json": () => import('./wedding-shoot_CWOkXirB.mjs')}), () => "../../data/service/*.json");
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "title": "Services" }, { "default": ($$result2) => renderTemplate` ${renderComponent($$result2, "Header", Header, { "client:load": true, "client:component-hydration": "load", "client:component-path": "C:/Users/aradh/git/MMM/src/components/Header.svelte", "client:component-export": "default" })} ${maybeRenderHead()}<img src="/imagePlaceholder.svg" alt="" class="h-[80vh] w-auto m-auto"> <div class="pt-20 md:p-10 p-2 m-auto rounded-2xl md:w-[80%] w-[95%] bg-secondary"> <h1 class="text-4xl text-white">Services</h1> ${services.map((el) => renderTemplate`${renderComponent($$result2, "ServiceCardLong", $$ServiceCardLong, { "data": el })}`)} </div> ` })}`;
}, "C:/Users/aradh/git/MMM/src/pages/services/index.astro", void 0);

const $$file$2 = "C:/Users/aradh/git/MMM/src/pages/services/index.astro";
const $$url$2 = "/services";

const index$1 = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
    __proto__: null,
    default: $$Index$1,
    file: $$file$2,
    url: $$url$2
}, Symbol.toStringTag, { value: 'Module' }));

var __freeze = Object.freeze;
var __defProp = Object.defineProperty;
var __template = (cooked, raw) => __freeze(__defProp(cooked, "raw", { value: __freeze(raw || cooked.slice()) }));
var _a;
const $$Astro$7 = createAstro();
const $$Test = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$7, $$props, $$slots);
  Astro2.self = $$Test;
  let dukkar = "& Astro";
  return renderTemplate(_a || (_a = __template(['<head><script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"><\/script>', "</head> <body", `> <h1 x-text="message">sdf</h1> <button type="button" @click="message = 'Hello world'">Click</button> <img src="{{src}}" alt="" srcset=""> </body><!-- 
    <div
    x-data=\`{
        search: '',
        
        items: ['foo', 'bar', 'baz'],
        
        get filteredItems() {
            return this.items.filter(
            i => i.startsWith(this.search)
            )
        }
    }\`
    >
    <input x-model="search" placeholder="Search..." />
    <p x-text=""></p>
    <ul>
        <template x-for="item in filteredItems" :key="item">
            <li x-text="item"></li>
        </template>
    </ul>
</div>

<div
x-data="{
    search:'aaa',
    items:['foo','bar','bax'],
    get getRes(){   
        return this.items.filter( 
        i => i.startsWith(this.search)
        )
    }
}"
>
<input type="text" name="" x-model="search" id="" placeholder="../" />
<p x-text="getRes"></p>
</div> -->`], ['<head><script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"><\/script>', "</head> <body", `> <h1 x-text="message">sdf</h1> <button type="button" @click="message = 'Hello world'">Click</button> <img src="{{src}}" alt="" srcset=""> </body><!-- 
    <div
    x-data=\\\`{
        search: '',
        
        items: ['foo', 'bar', 'baz'],
        
        get filteredItems() {
            return this.items.filter(
            i => i.startsWith(this.search)
            )
        }
    }\\\`
    >
    <input x-model="search" placeholder="Search..." />
    <p x-text=""></p>
    <ul>
        <template x-for="item in filteredItems" :key="item">
            <li x-text="item"></li>
        </template>
    </ul>
</div>

<div
x-data="{
    search:'aaa',
    items:['foo','bar','bax'],
    get getRes(){   
        return this.items.filter( 
        i => i.startsWith(this.search)
        )
    }
}"
>
<input type="text" name="" x-model="search" id="" placeholder="../" />
<p x-text="getRes"></p>
</div> -->`])), renderHead(), addAttribute(`{
        message: "I Love Alpine ${dukkar}",
        src: " favicon.png",
    }`, "x-data"));
}, "C:/Users/aradh/git/MMM/src/pages/test.astro", void 0);

const $$file$1 = "C:/Users/aradh/git/MMM/src/pages/test.astro";
const $$url$1 = "/test";

const test = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
    __proto__: null,
    default: $$Test,
    file: $$file$1,
    url: $$url$1
}, Symbol.toStringTag, { value: 'Module' }));

const $$Astro$6 = createAstro();
const $$CTA = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$6, $$props, $$slots);
  Astro2.self = $$CTA;
  return renderTemplate`${maybeRenderHead()}<div class="md:h-[100vh] h-[70vh] w-auto items-start flex flex-col justify-between md:items-center relative" data-astro-cid-4xty6sx2> <img src="/logo_white.svg" alt="" srcset="" class="md:w-[80vw] w-full md:h-[60%] h-[40%] flex m-auto mt-36" data-astro-cid-4xty6sx2> <p class="text-normal mx-2 md:text-xl text-center md:mx-[15%] m-auto font-semibold tracking-[0.15rem] text-white" data-astro-cid-4xty6sx2>
One Stop Solution for all your Marketing needs! Digital Ads, Website
        Development, Brand Awareness ??? Wegot you covered
</p> <!-- <h1 class="text-[200px] text-center mt-10 text-white">MIST</h1> --> <div class="bg absolute -z-10" data-astro-cid-4xty6sx2> <video src="/mainBg.mp4" autoplay loop="true" class="opacity-40 h-screen" data-astro-cid-4xty6sx2></video> </div> </div> <br data-astro-cid-4xty6sx2> `;
}, "C:/Users/aradh/git/MMM/src/components/CTA.astro", void 0);

const $$Astro$5 = createAstro();
const $$Marquee = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$5, $$props, $$slots);
  Astro2.self = $$Marquee;
  Astro2.props;
  const _imgs = await Astro2.glob(/* #__PURE__ */ Object.assign({"../../public/brands/At Ease Logo.png": () => import('./At Ease Logo_BH0arQRz.mjs'),"../../public/brands/Bhanu_s Academny.png": () => import('./Bhanu_s Academny_T6IcyAs-.mjs'),"../../public/brands/Logo PNG.png": () => import('./Logo PNG_DoIN2tdh.mjs'),"../../public/brands/Logo R1.png": () => import('./Logo R1_8UXcQy7J.mjs'),"../../public/brands/ROUND.png": () => import('./ROUND_nor_ItFF.mjs'),"../../public/brands/The Hair Studio Logo 02.png": () => import('./The Hair Studio Logo 02_CNBEv3yY.mjs'),"../../public/brands/panna logo 2.png": () => import('./panna logo 2_Bg4WsK6b.mjs')}), () => "../../public/brands/*.png");
  return renderTemplate`${maybeRenderHead()}<div class="w-[98vw] overflow-hidden mt-[10vh]" data-astro-cid-tpudeaz7> <p class="bg-bg text-center text-primary px-5 font-semibold md:text-4xl my-10 p-2 text-xl" data-astro-cid-tpudeaz7>
Brands We Have Worked With
</p> <div class="md:w-[4000px] w-[1400px] justify-between overflow-hidden flex" id="marq" data-astro-cid-tpudeaz7> ${_imgs.map((el) => renderTemplate`<div class=" w-20 p-2 h-20 md:w-40 md:h-40  flex items-center text-4xl hover:scale-110 rounded-xl hover:bg-white/70 backdrop-blur-xl transition-all text-center elems" data-astro-cid-tpudeaz7> ${renderComponent($$result, "Image", $$Image, { "src": el.default, "alt": "", "srcset": "", "data-astro-cid-tpudeaz7": true })} </div>`)} ${_imgs.map((el) => renderTemplate`<div class=" w-20 p-2 h-20 md:w-40 md:h-40  flex items-center text-4xl hover:scale-110 rounded-xl hover:bg-white/70 backdrop-blur-xl transition-all text-center elems" data-astro-cid-tpudeaz7> ${renderComponent($$result, "Image", $$Image, { "src": el.default, "alt": "", "srcset": "", "data-astro-cid-tpudeaz7": true })} </div>`)} </div> </div> `;
}, "C:/Users/aradh/git/MMM/src/components/Marquee.astro", void 0);

const $$Astro$4 = createAstro();
const $$ServiceCard = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$4, $$props, $$slots);
  Astro2.self = $$ServiceCard;
  const { title, description, src = "/imagePlaceholder.svg" } = Astro2.props;
  return renderTemplate`${maybeRenderHead()}<div id="serv" class="flex flex-col justify-between w-60 md:w-80 rounded-lg md:h-[500px] h-[450px] md:m-12 m-6 border-2 border-secondary shadow-lg hover:scale-110 transition-all hover:shadow-primary bg-bg" data-astro-cid-5cs2w34i> <div class="w-2/3 h-[29%] m-auto my-[1%] overflow-hidden" data-astro-cid-5cs2w34i> <img${addAttribute(src, "src")} alt="" srcset="" class="h-full m-auto" data-astro-cid-5cs2w34i> </div> <div class="w-full h-[60%] rounded-t-[2.5rem] rounded-b-md overflow-hidden text-white bg-secondary hover:h-[90%] transition-all" data-astro-cid-5cs2w34i> <h1 class="m-5 md:text-3xl text-xl font-semibold font-primaryFont" data-astro-cid-5cs2w34i> ${title} </h1> <p class="relative mx-5 mt-5 md:text-lg text-sm h-[60%] tracking-wider overflow-hidden" data-astro-cid-5cs2w34i> ${description} <span class="bg-gradient-to-b from-transparent to-secondary w-full absolute h-10 bottom-0 left-0" data-astro-cid-5cs2w34i></span> </p> <div id="reachOut" class="md:text-xl hidden cursor-pointer my-2 text-base text-black w-[80%] m-auto bg-primary md:px-5 md:py-2 px-2 py-1 rounded-full font-semibold hover:scale-110 transition-all" data-astro-cid-5cs2w34i> <a href="/contact" data-astro-cid-5cs2w34i>Reach Out to Us</a> </div> </div> </div>  `;
}, "C:/Users/aradh/git/MMM/src/components/util/ServiceCard.astro", void 0);

const $$Astro$3 = createAstro();
const $$Services = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$3, $$props, $$slots);
  Astro2.self = $$Services;
  return renderTemplate`${maybeRenderHead()}<h1 class="bg-bg text-center text-primary px-5 font-semibold md:text-4xl p-2 text-3xl">
Service We Offer
</h1> <div class="p-2 overflow-auto bg-bg"> <div class="overflow-x-scroll no-scrollbar"> <div class="flex w-max bg-scroll"> ${[1, 2, 3, 4, 5].map((el) => renderTemplate`${renderComponent($$result, "ServiceCard", $$ServiceCard, { "title": `Service ${el}`, "description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enimaccusamus adipisci earum voluptate quia quae voluptatem expeditaoptio voluptatum sapiente itaque omnis mollitia et necessitatibusinventore, corrupti iure dolorem! Voluptatibus, corrupti explicabo?" })}`)} </div> </div> </div>`;
}, "C:/Users/aradh/git/MMM/src/components/Services.astro", void 0);

const $$Astro$2 = createAstro();
const $$Spacer = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$2, $$props, $$slots);
  Astro2.self = $$Spacer;
  return renderTemplate`${maybeRenderHead()}<div class="w-full h-auto relative" data-astro-cid-43nuhumo> <div class="w-full h-80 absolute bg-gradient-to-b from-bg to-transparent z-20" data-astro-cid-43nuhumo></div> <div class="left-0 right-0 w-full h-full opacity-20 absolute bg-bg -z-10" data-astro-cid-43nuhumo></div> <div class="imgBg" data-astro-cid-43nuhumo></div> <!-- <img
        src="/Spacer1.jpg"
        alt=""
        srcset=""
        class="h-screen md:w-screen md:h-auto -z-20 opacity-40"
    /> --> <div class="flex flex-col absolute top-[50%] items-center left-[50%] translate-x-[-50%] translate-y-[-50%]" data-astro-cid-43nuhumo> <h1 class="md:text-[9rem] text-8xl text-center text-primary/80 decoration-from-font" data-astro-cid-43nuhumo>
Hire Us
</h1> <div class="button top-96 right-10" data-astro-cid-43nuhumo> <a href="/contact" data-astro-cid-43nuhumo>Contact Us</a> </div> <div class="button top-96 right-10" data-astro-cid-43nuhumo> <a href="/contact" data-astro-cid-43nuhumo>Services</a> </div> </div> <div class="w-full h-80 bottom-0 absolute bg-gradient-to-t from-bg to-transparent z-20" data-astro-cid-43nuhumo></div> </div> `;
}, "C:/Users/aradh/git/MMM/src/components/Spacer.astro", void 0);

const $$Astro$1 = createAstro();
const $$About = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$1, $$props, $$slots);
  Astro2.self = $$About;
  return renderTemplate`${maybeRenderHead()}<div class="text-white" id="about" data-astro-cid-v2cbyr3p> <p class="bg-bg text-center text-primary px-5 font-semibold md:text-4xl my-10 p-2 text-xl" data-astro-cid-v2cbyr3p>
About Us
</p> <p class="md:text-lg text-base tracking-wider p-2 md:w-[70%] w-[95%] m-auto" data-astro-cid-v2cbyr3p>
At <b class="text-primary text-2xl" data-astro-cid-v2cbyr3p>M</b>ist <b class="text-primary text-2xl" data-astro-cid-v2cbyr3p>M</b>edia <b class="text-primary text-2xl" data-astro-cid-v2cbyr3p>M</b>arketing, our track record
        speaks for itself:<br data-astro-cid-v2cbyr3p> With over <u class="text-primary text-xl" data-astro-cid-v2cbyr3p>
7 years of experience</u>, we've delighted over <b class="text-primary text-2xl" data-astro-cid-v2cbyr3p>50 clients</b> and
        counting.... <br data-astro-cid-v2cbyr3p> Renowned for crafting compelling content that drives
        millions of views and leads, we specialize in tailoring each piece to our
        clients' unique vibe and audience. Our approach combines authenticity with
        innovation, consistently delivering measurable outcomes. By infusing joy
        and dynamism into digital storytelling, we transform every project into an
        opportunity to inject vitality and relevance into today's digital landscape.
        We excel in effective <u class="text-primary text-xl" data-astro-cid-v2cbyr3p>Social Media and Marketing strategies, enhancing Brand Awareness
            and Online Communications.</u> Utilizing metrics, we refine digital marketing campaigns to guide teams
        toward achieving their online presence goals. <br data-astro-cid-v2cbyr3p> <!-- <ul class="text-xl tracking-wider p-2 w-[70%] m-auto text-justify">
            <b class="text-primary text-2xl">
                Our clientes includes esteemed brands such as:-
            </b>
            <li>Sayaji Hotels Indore,</li><li>Radisson,</li>
            <li>Marriott,</li>
            <li>IBIS STYLES,</li>
            <li>Crown Plaza Jaipuria Group of Institutions,</li>
            <li>Swiggy,</li>
            <li>Joie Learning,</li>
            <li>Key Elements,</li>
            <li>Rely,</li>
            <li>Bhanu's,</li>
            <li>Cafe at Ease,</li>
            <li>Urban Theka,</li>
            <li>Ramashray,</li>
            <li>and many others...</li>
        </ul> --> </p> </div> `;
}, "C:/Users/aradh/git/MMM/src/components/About.astro", void 0);

const $$Astro = createAstro();
const $$Index = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Index;
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "title": "Mist Media Marketing Agency" }, { "default": ($$result2) => renderTemplate` ${renderComponent($$result2, "Header", Header, { "client:load": true, "client:component-hydration": "load", "client:component-path": "C:/Users/aradh/git/MMM/src/components/Header.svelte", "client:component-export": "default" })} ${renderComponent($$result2, "CTA", $$CTA, {})} ${renderComponent($$result2, "About", $$About, {})} ${renderComponent($$result2, "Marquee", $$Marquee, {})} ${renderComponent($$result2, "Spacer", $$Spacer, {})} ${renderComponent($$result2, "Services", $$Services, {})} ` })}`;
}, "C:/Users/aradh/git/MMM/src/pages/index.astro", void 0);

const $$file = "C:/Users/aradh/git/MMM/src/pages/index.astro";
const $$url = "";

const index = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
    __proto__: null,
    default: $$Index,
    file: $$file,
    url: $$url
}, Symbol.toStringTag, { value: 'Module' }));

export { _slag_ as _, index as a, contact as c, index$1 as i, test as t };
